server:
  port: 9003

spring:
  application:
    name: langchain4j-03boot-integration

langchain4j:
  open-ai:
    chat-model:
      api-key: ${AliQwen_Key}
      model-name: qwen-plus
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1