server:
  port: 9994
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: langchain4j-14chat-mcp

langchain4j:
  community:
    dashscope:
      streaming-chat-model:
        api-key: ${AliQwen_Key}
        model-name: qwen-plus
      chat-model:
        api-key: ${AliQwen_Key}
        model-name: qwen-plus